name = "chat-proxy"
main = "src/index.js"
compatibility_date = "2024-10-01"

[vars]
# Optional: lock CORS to your site origin here; you can also set it in dashboard
# ALLOWED_ORIGIN = "https://your-site.example"

# Add your secret via: wrangler secret put GEMINI_API_KEY
